# Generated by Django 4.0.6 on 2022-08-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_rename_file_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='downloadpath',
            field=models.FilePathField(default=1, max_length=300, path='media/files', recursive=True),
            preserve_default=False,
        ),
    ]
