# Generated by Django 4.0.6 on 2022-08-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_files_downloadpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='downloadpath',
            field=models.FilePathField(max_length=300, path='/home/cordei/Desktop/School/AYOS 4 (LAST DANCE)/CSC3003S/Assignments/Code/csc3003-lightweight-file-manager/media', recursive=True),
        ),
    ]
