# Generated by Django 4.0.6 on 2022-08-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0008_alter_files_downloadpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='settings.BASE_DIR/media/files/'),
        ),
    ]
