# Generated by Django 4.0.6 on 2022-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0010_alter_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='downloadpath',
            field=models.FilePathField(default='2022-04-21_18-35.png', path='media/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
