# Generated by Django 4.0.6 on 2022-08-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0011_alter_files_downloadpath_alter_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='downloadpath',
        ),
    ]
