# Generated by Django 4.1 on 2022-09-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0016_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
