# Generated by Django 4.1 on 2022-09-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0020_alter_files_file_alter_files_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=models.TextField(blank=True, max_length=20)),
        ),
        migrations.AlterField(
            model_name='files',
            name='folder',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
