# Generated by Django 4.1 on 2022-09-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0021_alter_files_file_alter_files_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='filedetails',
        ),
        migrations.RemoveField(
            model_name='files',
            name='filename',
        ),
    ]
