# Generated by Django 4.1 on 2022-09-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0022_remove_files_filedetails_remove_files_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
