# Generated by Django 4.1 on 2022-09-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0026_alter_files_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
