# Generated by Django 4.1 on 2022-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0027_delete_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=models.CharField(blank=True, choices=[('size_1-9', '1-9'), ('size_10-49', '10-49'), ('size_50-99', '50-99'), ('size_100', '100+')], default='size_1-9', max_length=20, null=True)),
        ),
        migrations.AlterField(
            model_name='files',
            name='folder',
            field=models.CharField(blank=True, choices=[('size_1-9', '1-9'), ('size_10-49', '10-49'), ('size_50-99', '50-99'), ('size_100', '100+')], default='size_1-9', max_length=20, null=True),
        ),
    ]
