# Generated by Django 4.1 on 2022-09-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0028_alter_files_file_alter_files_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='folder',
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
