# Generated by Django 4.1 on 2022-09-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0030_files_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='folder',
        ),
    ]
