# Generated by Django 4.1 on 2022-09-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0031_remove_files_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='uploadedFiles/'),
        ),
    ]
